#! /bin/bash

./gradlew ktlintCheck

status=$?
if [ "$status" != 0 ]; then
  echo "ktlintFormat failed, format code again manually!"
  exit 1
fi

./gradlew testDebugUnitTest
./gradlew testReleaseUnitTest

status=$?
if [ "$status" = 0 ]; then
  printf "\nCode style is good\nAll unit tests passed"
else
  echo "Some unit tests are failing!"
  exit 1
fi
